### ISSUE TITLE
no Campfire menu in dropdown list

### ISSUE THREAD

**Issue by humbroll** [mstepniowski/AdiumCampfire#1]
I install Campfie. but there is no Campfire menu in dropdown list(File->Add Account)
Any problem?
want use this plugin! :)

**Comment by mstepniowski** [comment]
That's weird. What version of OS X and Adium are you using? 

I will upload a binary version of plugin before the end of this week for you and others to test, as it's easy to make errors when setting development environment for compilation.

**Comment by mstepniowski** [comment]
Unfortunately the rewrite of the networking stack was delayed due to unforeseen circumestances. Please try using the [AdiumCampfire 0.0.1 pre-beta binary](https://github.com/downloads/zuber/AdiumCampfire/AdiumCampfire.AdiumPlugin.zip) in the meantime.

**Comment by jamesroscoe** [comment]
I had the same problem with the current AdiumCampfire source. The pre-beta binary from the commend above worked like a charm. Feedback: error messages on the connection weren't very good (I initially entered the domain wrong so it got as far as 30% connected but wouldn't go any farther. No error message was ever presented). I'm looking forward to making great use of this. Thanks!

**Comment by mstepniowski** [comment]
Thanks for the feedback James. I hope you're making good use of the plugin.

I've created a ticket #2 to add better error notifications to the project. I will also look at the compilation issues.

**Comment by humbroll** [comment]
Thanks James and Zuber.
It's working perfectly now. :)

**Comment by humbroll** [comment]
Zuber, Can you push the newest code?:)
