### ISSUE TITLE
Sent chat items are duplicated

### ISSUE THREAD

**Issue by jamesroscoe** [mstepniowski/AdiumCampfire#3]
When you send a chat item it is repeated back to you by Campfire within a couple of seconds. That returned item is currently being displayed but should probably be suppressed.

**Comment by jflo** [comment]
I am seeing this as well.

**Comment by dragos** [comment]
Me too. It would be cool to fix this..

**Comment by mstepniowski** [comment]
There is no robust error-handling in AdiumCampfire plugin yet (I'm working on the engine rewrite) so seeing your message echoed back is the only way to be sure that it got to the server. OTOH enough people seem to be annoyed by this issue. I will probably review and merge @pmhood's #4 changeset today, adding filtering out chat messages from the logged in user and implementing basic support for uploads.

**Comment by mstepniowski** [comment]
I've just merged @pmhood's changeset and uploaded [a new binary](https://github.com/downloads/zuber/AdiumCampfire/AdiumCampfire-0.1-20110504.zip) with the fix. Closing.
